package model.trainer;

public enum TrainingType {
	PERSONAL_AEROBIC,
	PERSONAL_STRENGTH,
	PERSONAL_BALANCEandSTABILITY,
	PERSONAL_COORDINATIONandAGILITY,
	PERSONAL_FLEXIBILITYandMOBILITY,
	GROUP_AEROBIC,
	GROUP_STRENGTH,
	GROUP_BALANCEandSTABILITY,
	GROUP_COORDINATIONandAGILITY,
	GROUP_FLEXIBILITYandMOBILITY
}
